### ISSUE TITLE
Roadmap to Version 0.2.0

### ISSUE THREAD

**Issue by AlexCCavaco** [AlexCCavaco/obsidian-exercises#1]
# Exercises

- [X] Select — $select (0.1.0)
- [X] Text — $input and $line (0.1.0)
- [X] Match — $match (0.1.0)
- [x] Multiple Choice — $choice (0.1.2)
- [ ] Order Words to form a sentence — $sentence

# Other

- [ ] Support Images on Match Exercises
- [ ] Support Images on Choice Exercises
- [x] Support Markdown inside Code Blocks (0.1.2)
